version: "3.8"
services:
  app:
    image: ghcr.io/whi-tw/docker-dnsmasq:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./config:/etc/dnsmasq.d
